Repository MaeumGaGym/MaeumGaGym_Frontend, pull requests merged in 2024-03, with the labels that each got.

#41 📝 :: Shop 메인 페이지 추가
  packages/ui/assets/HalfStar.tsx
  packages/ui/assets/index.tsx
  service/user/next.config.js
  service/user/src/app/shop/Slider.tsx
  service/user/src/app/shop/page.tsx
  service/user/src/assets/shopBanner/banner1.png
  service/user/src/assets/tentativeBannerIcon.png
  service/user/src/components/banner.tsx
  service/user/src/components/shop/BasketAlert.tsx
  service/user/src/components/shop/DetailItem.tsx
  service/user/src/components/shop/ItemLayout.tsx
  service/user/src/components/shop/SelectItemType.tsx
  service/user/src/components/shop/ShowStar.tsx
  service/user/src/components/shop/SimpleItem.tsx
  service/user/src/styles/globals.css
Labels: UI

#43 🥚 :: build error 수정
  service/user/src/components/shop/DetailItem.tsx
  service/user/src/components/shop/ItemLayout.tsx
  service/user/src/components/shop/SelectItemType.tsx
  service/user/src/components/timer.tsx
Labels: bug

#44 🥚 :: 타이머 오류 수정
  service/user/src/components/timer.tsx
Labels: bug

#46 Feature/#45 timer refactor
  service/user/src/components/timer.tsx
Labels: refactor

#49 🥚 :: json parse 오류 해결
  service/user/src/components/timer.tsx
Labels: bug

#58 EDIT :: privacy page
  service/admin/src/app/privacy/PrivacySection.tsx
  service/admin/src/app/privacy/page.tsx
  service/main/src/app/privacy/PrivacySection.tsx
  service/main/src/app/privacy/page.tsx
  service/user/src/app/privacy/PrivacySection.tsx
  service/user/src/app/privacy/page.tsx
Labels: refactor

#60 ADD :: docker env
  .github/workflows/deploy-admin.yml
  .github/workflows/deploy-main.yml
  .github/workflows/deploy-user.yml
  service/admin/Dockerfile
  service/admin/src/apis/axios.ts
  service/main/Dockerfile
  service/main/next.config.js
  service/main/src/apis/axios.ts
  service/user/Dockerfile
  service/user/src/apis/axios.ts
Labels: setting

#62 FIX :: env
  service/admin/Dockerfile
  service/main/Dockerfile
  service/user/Dockerfile
Labels: bug

#64 이슈/PR 템플릿 추가
  .github/ISSUE_TEMPLATE/error.yml
  .github/ISSUE_TEMPLATE/explanation.yml
  .github/ISSUE_TEMPLATE/function.yml
  .github/ISSUE_TEMPLATE/refactoring.yml
  .github/pull_request_template.md
Labels: dependencies

#65 FEAT :: Add OWENRS file and Change PR Template
  .github/pull_request_template.md
  OWNERS
Labels: kind/리펙토링, size/M, lgtm

#66 PR :: 필수약관과 선택약관까지 동의 했을 때 모두 동의 되도록 수정
  service/main/src/app/@auth/(.)signin/TermsModal.tsx
Labels: kind/버그, kind/기능
